### ISSUE TITLE
Can not blur screen edges

### ISSUE THREAD

**Issue by proxiti** [chrisbanes/haze#109]
Blur effect can not reach the edge.
![ff7aecbbc1af99d5842a8623b01192a](https://github.com/chrisbanes/haze/assets/25367586/045659bb-ccfb-49d5-b168-1b683b773580)

**Comment by chrisbanes** [comment]
Do you really think this report is good enough? Theres:

- No information on how you're using Haze? Show me code.
- What version of Haze?

**Comment by proxiti** [comment]
> Do you really think this report is good enough? Theres:
> 
> * No information on how you're using Haze? Show me code.
> * What version of Haze?

Sorry, here are the details.

Compose version: 1.6.0
Haze version: 0.4.5
```kotlin
Box {
    Image(
        modifier = Modifier
            .fillMaxSize()
            .haze(
                state = hazeState,
                backgroundColor = Color.Transparent,
                tint = Color.Transparent,
                noiseFactor = 0f
            ),
        painter = painterResource(
            id = R.drawable.bg
        ),
        contentDescription = "",
        contentScale = ContentScale.Crop
    )

    Box(
        modifier = Modifier
            .align(Alignment.BottomStart)
            .hazeChild(state = hazeState)
            .height(80.dp)
            .fillMaxWidth(),
    )
}
```
Thanks for looking into this.

**Comment by chrisbanes** [comment]
The PR linked above should fix this for Android. The Skiko platforms are more difficult, so I've opened #114 to track those.
