### ISSUE TITLE
Strange behaviour during scaling content with HAZE blur

### ISSUE THREAD

**Issue by skilz2012** [chrisbanes/haze#123]
## Information

  - Haze version: 0.5.0
  - Platform: Android

## Expected Behavior
Scaling without moving bottom blur bg

## Actual Behavior
[wrong_logic.webm](https://github.com/chrisbanes/haze/assets/13544274/e6c5a8d3-ccf9-48a8-85b3-a0cf7fbade9f)

## Steps to Reproduce the Problem

  1. make simple animation for scale all content:
  
<img width="556" alt="image" src="https://github.com/chrisbanes/haze/assets/13544274/cbadbab3-2376-45f8-a0ae-57d4fab0bbae">

  2.Haze(blur) inside to HomeScreen():
  
<img width="676" alt="image" src="https://github.com/chrisbanes/haze/assets/13544274/63c73adc-255e-4aaa-bf4e-f352b1b6ccdc">

It's debugger result for case if 
scale 1x:
<img width="1224" alt="image" src="https://github.com/chrisbanes/haze/assets/13544274/724d2e1c-9ef9-4178-8af2-fee6f978a11c">

Scale: 0.8x:
<img width="1240" alt="image" src="https://github.com/chrisbanes/haze/assets/13544274/a064d1fb-19a2-40ab-b0a4-0dfb8901a48f">

p.s. if need can send project for fast testing

**Comment by chrisbanes** [comment]
There's not much we can do about this. We can't get access to the `graphicsLayer` and so have no idea what transforms you're applying.

**Comment by skilz2012** [comment]
@chrisbanes, will Haze not work correctly with a simple scale of the main container?

**Comment by chrisbanes** [comment]
That is what I put above.
