### ISSUE TITLE
Support dynamic blur radius

### ISSUE THREAD

**Issue by proxiti** [chrisbanes/haze#138]
## Information

  - Haze version: 0.5.3
  - Platform: Android13
  - Compose version: 1.6.0

## Expected Behavior
Support dynamic blur radius so that I can achieve scrolling effect.

## Steps to Reproduce the Problem
Simply use button to change blur radius: 
```kotlin
val hazeState = remember { HazeState() }

var noiseFactor by remember {
    mutableFloatStateOf(20f)
}

Box {
    Image(
        modifier = Modifier
            .fillMaxSize()
            .haze(
                state = hazeState
            ),
        painter = painterResource(
            id = R.drawable.test
        ),
        contentDescription = "",
        contentScale = ContentScale.Crop
    )

    Box(
        modifier = Modifier
            .align(Alignment.Center)
            .padding(horizontal = 14.dp)
            .height(80.dp)
            .fillMaxWidth()
            .hazeChild(
                state = hazeState,
                shape = RoundedCornerShape(20.dp),
                style = HazeStyle(
                    noiseFactor = noiseFactor,
                    tint = Color.Black.copy(.6f)
                )
            ),
    )

    Button(onClick = { noiseFactor = 0f }) {
        Text(text = "click me")
    }
}
```

**Comment by chrisbanes** [comment]
I don't understand what the bug is here? 

You're setting the noiseFactor and not the `blurRadius`. There's a `blurRadius` property on [HazeStyle](https://chrisbanes.github.io/haze/api/haze/dev.chrisbanes.haze/-haze-style/) which sounds like what you want to use.

**Comment by proxiti** [comment]
> I don't understand what the bug is here?
> 
> You're setting the noiseFactor and not the `blurRadius`. There's a `blurRadius` property on [HazeStyle](https://chrisbanes.github.io/haze/api/haze/dev.chrisbanes.haze/-haze-style/) which sounds like what you want to use.

Sorry, this should be blurRadius. I've tested again and there are no such issues.
