### ISSUE TITLE
Support RoundedRect areas

### ISSUE THREAD

**Issue by MohamedRejeb** [chrisbanes/haze#14]
Hi Chris,
Thanks for this amazing Modifier, it's really helpful.

I have similar use case but I need to add a border radius to the area, I'm working on implementing this feature and I will create a PR when it's ready.

I'm going to create a new public composable that accepts a `List<RoundRect>`

**Comment by chrisbanes** [comment]
Yeah, this is on my list to look at. It's unfortunately not that simple on the Skia implementation, as a lot of things are manually written in a runtime shader. It is achievable though.
