### ISSUE TITLE
Can i use haze with Jetpack compose Popup?

### ISSUE THREAD

**Issue by VahidGarousi** [chrisbanes/haze#172]
## Information

  - Haze version: 0.6.2
  - Platform: Android

## Expected Behavior
![image](https://github.com/chrisbanes/haze/assets/19606714/273e183d-7f06-46cb-9b5e-0126e6648cfc)

## Steps to Reproduce the Problem
```
Popup(
            properties = PopupProperties(
                dismissOnBackPress = true,
                dismissOnClickOutside = true,
                focusable = true,
                excludeFromSystemGesture = false
            ),
            popupPositionProvider = remember(traderLegendInformation.boundsInRoot) {
                LegendPopupOffsetPositionProvider(
                    traderLegendInformation.boundsInRoot,
                    triangleHeightInPx = triangleHeightInPx
                )
            },
            onDismissRequest = remember { { shouldShowTooltip = null } }
        ) {
            TooltipShowMoreLarge(
                text = traderLegendInformation.legend.title
            )
        }
```

**Comment by chrisbanes** [comment]
Have you actually tried this before creating an issue? The fact that there's an "Actual Behavior" section which you ignored points to the fact that you didn't.

Clue: it already works.

**Comment by VahidGarousi** [comment]
> Have you actually tried this before creating an issue? The fact that there's an "Actual Behavior" section which you ignored points to the fact that you didn't.
> 
> Clue: it already works.

Yes, I attempted to implement the provided code, but unfortunately, I didn't observe any noticeable changes in behavior. I'll revisit the issue tomorrow and provide an update accordingly. Thank you for your patience.

**Comment by chrisbanes** [comment]
Have a look at the [DialogSample](https://github.com/chrisbanes/haze/blob/main/sample/shared/src/commonMain/kotlin/dev/chrisbanes/haze/sample/DialogSample.kt#L60). Swap `Dialog` to `Popup` and it works as expected.
