### ISSUE TITLE
"Android is missing the noise effect"

### ISSUE THREAD

**Issue by ColtonIdle** [chrisbanes/haze#19]
https://chrisbanes.github.io/haze/faq/#android-jetpack-compose

"Android is missing the noise effect..." I think this was added in 0.2.0?

**Comment by David8aO** [comment]
It works.
Make sure youre using [1.6.0-alpha08] version of compose and your topAppBar/navigationBar container color is set to transparent

**Comment by chrisbanes** [comment]
Ah, the docs publish task failed due to an incorrect protection rule. Anyway, just fixed it and re-published the docs.
