### ISSUE TITLE
Haze background color differs from specified one

### ISSUE THREAD

**Issue by fvilarino** [chrisbanes/haze#20]
## Description
The background behind the haze rectangle does not seem to honor the specified color.

## Details
In version 0.2.0 the background color specified in the haze modifier does not appear to render correctly. In my use case the background is `MaterialTheme.colorScheme.surface` and I configure haze as shown [here](https://github.com/fvilarino/Weather-Sample/blob/68e628491c69c8f976ce12e2d5e2c3f41e8e8ea9/ui/feature/search/src/main/kotlin/com/francescsoftware/weathersample/ui/feature/search/weather/ui/SinglePaneWeatherContent.kt#L130) and below
```
.haze(
    headerSize.toRect(),
    backgroundColor = MaterialTheme.colorScheme.surface,
    tint = MaterialTheme.colorScheme.surface.copy(alpha = .5f),
    blurRadius = 16.dp,
)
```
The app background is defined as shown here
```
@Composable
private fun AppBackground(
    modifier: Modifier = Modifier,
    content: @Composable () -> Unit,
) {
    Box(
        modifier = modifier
            .background(
                Brush.verticalGradient(
                    BackgroundGradientStart to MaterialTheme.colorScheme.surface,
                    1f to MaterialTheme.colorScheme.surfaceColorAtElevation(2.dp),
                ),
            ),
    ) {
        content()
    }
}
```
with `BackgroundGradientStart` set to .33f, so the top 1/3 of the screen is Surface color and the bottom 2/3 gradually ligtens said color.

## Samples
In haze 0.1.0 the translucent pane blends with the background:
![haze_0 1 0](https://github.com/chrisbanes/haze/assets/2680481/d145cd3e-3c69-4af9-9c88-4396e7db93c0)

In haze 0.2.0 the pane is visible as a lighter tone:
![haze_0 2 0](https://github.com/chrisbanes/haze/assets/2680481/fdc802c4-4ea5-491d-8379-010fa84e8769)

For context, this is the pane with content behind:
![Screenshot_1699026730](https://github.com/chrisbanes/haze/assets/2680481/b8a02a3c-82f2-44f4-aea1-3b7bd3c6ab85)

**Comment by chrisbanes** [comment]
Thanks for the report. This likely because of the noise effect texture which we’re using on Android. I’ll investigate over the weekend.
