### ISSUE TITLE
Dialog blur offset

### ISSUE THREAD

**Issue by Stavrenas** [chrisbanes/haze#200]
## Information

  - Haze version: 0.7.0
  - Platform: Native Android (min sdk 30, target 34)

## Expected Behavior
Dialog is uniformly blurred

![Screenshot_2024-04-29-13-36-48-091_ai datawise finstreet](https://github.com/chrisbanes/haze/assets/7922854/478473ba-ed1d-4711-a014-949c1246ed41)

This screenshot was generated by enabling the fullscreen mode 
(activity.window.decorView.systemUiVisibility = View.SYSTEM_UI_FLAG_FULLSCREEN)

## Actual Behavior
Dialog's blur is offset by the top (or bottom) bar when not in fullscreen

![Screenshot_2024-04-29-13-38-47-935_ai datawise finstreet](https://github.com/chrisbanes/haze/assets/7922854/08c1ab75-790e-408e-be84-19dea4f9aaa8)

## Steps to Reproduce the Problem

  1. Create a new native android project
  2. Copy-paste the sample code for the [dialog preview](https://github.com/chrisbanes/haze/blob/main/sample/shared/src/commonMain/kotlin/dev/chrisbanes/haze/sample/DialogSample.kt)
  3. Launch the app on the device

Unfortunately, I can't compile the source code to do any debugging (yet).

**Comment by chrisbanes** [comment]
I'm afraid that I can't reproduce this at all. If you can provide a sample which reproduces on an emulator then I can take a look.

**Comment by Stavrenas** [comment]
@chrisbanes sure, can you try this repo? https://github.com/Stavrenas/haze-offset

**Comment by chrisbanes** [comment]
I still can't recreate this an emulator or Pixel 8. 

I'm afraid that if this isn't reproducible on an emulator then it's almost certain to be a OEM/device specific issue, and there's not much I can do to help here really. What device and Android version are you using? 

FYI, the integration here is extremely simple: it's just a call to [`View.getLocationOnScreen`](https://github.com/chrisbanes/haze/blob/main/haze/src/androidMain/kotlin/dev/chrisbanes/haze/Platform.kt#L20).

**Comment by Stavrenas** [comment]
I'm on a Pixel 6 on an Ubuntu dev environment, however this happens also on a Windows machine with a Poco X4 GT device. 

I tried the same thing on the emulator, Pixel 8 (default settings) and the result is the same.
![pixel_8_emulator](https://github.com/chrisbanes/haze/assets/7922854/3f2e884d-faf8-4eb3-98ea-70fcfbcc4a34)

I'm starting to think, maybe it's jdk related? I'm on version 17, I'll try a newer one and update you

**Comment by chrisbanes** [comment]
So just to confirm, this only happens when deploying previews to device?
