### ISSUE TITLE
Position mismatch with scale transform

### ISSUE THREAD

**Issue by kasem-sm** [chrisbanes/haze#213]
## Information

  - Haze version: 0.7.1
  - Platform: Android

Position mismatch with android predictive back gesture. The blur moves along with the back animation while other UI elements are on their respective positions.

PS: I'm using decompose for navigation. The back animation code is similar to this - https://github.com/msasikanth/twine/blob/e5635d10afc3f4d0aea6310ed8c3c67af9a8d249/shared/src/androidMain/kotlin/dev/sasikanth/rss/reader/app/BackAnimation.kt#L42 

Screen recording :

https://github.com/chrisbanes/haze/assets/83884225/190a2358-ca81-4ca9-a921-33bd7dc27e5c

**Comment by ruishi01** [comment]
@chrisbanes I'm not sure if it's related to this issue, but I found that sometimes when there is global position change to the parent or child, the `onPlaced` is not called and the position is not updated which causes the blur area being off.  Can we add `GlobalPositionAwareModifierNode` to both AndroidHazeNode and `HazeChildNode` and update the position accordingly as well?

**Comment by chrisbanes** [comment]
@ruishi01 that doesn't sound related. Just opened #241

**Comment by kasem-sm** [comment]
https://github.com/user-attachments/assets/e559555c-e630-4ffd-97e1-b755ddcb7547

Latest alpha fixes the mismatch but the blur does not seems to be stable.

**Comment by chrisbanes** [comment]
>  the blur does not seems to be stable.

I don't think there's much that we can do about that. Same issue as before, we don't know what ancestor layer properties are being changed so can't adjust how we draw the content layer.

**Comment by kasem-sm** [comment]
I see. Thanks for the info.
