### ISSUE TITLE
Why hazy not work?

### ISSUE THREAD

**Issue by KirinHorse** [chrisbanes/haze#216]
## Information

  - Haze version: 0.7.1
  - Platform: Android Jetpack Compose

## Expected Behavior
 TopAppBar blur the background

## Actual Behavior
 TopAppBar has no effect
![Screenshot_2024-05-09-15-20-10-754_com wtkj app c](https://github.com/chrisbanes/haze/assets/11539294/a281c546-4296-48d4-b303-cecb4c29249d)

## Steps to Reproduce the Problem
```kotlin
@OptIn(ExperimentalMaterial3Api::class)
@Composable
fun Test() {
    val hazeState = remember { HazeState() }

    Box {
        LazyColumn(modifier = Modifier.fillMaxSize().haze(state = hazeState)) {
            item {
                Image(
                    painter = painterResource(id = R.drawable.main_bg),
                    contentDescription = null,
                    modifier = Modifier.fillMaxSize(),
                    contentScale = ContentScale.Crop,
                )
            }
        }
        LargeTopAppBar(
            colors = TopAppBarDefaults.largeTopAppBarColors(Color.Transparent),
            title = { Text(text = "Test Page") },
            modifier = Modifier.hazeChild(state = hazeState).fillMaxWidth(),
        )
    }
}
```

**Comment by chrisbanes** [comment]
I don't know what device you're using, but you code you attached above works in an API 34 emulator.

![Screenshot_1715240736](https://github.com/chrisbanes/haze/assets/227486/743b38cf-bdb1-409f-b7d7-764d1a3e7bc7)

**Comment by KirinHorse** [comment]
I tested it on a Xiaomi phone with android version 12 and API 31. But another Xiaomi phone with Android 14 and API 34 worked fine

**Comment by KirinHorse** [comment]
I found that haze uses a translucent scrim (overlay) for devices below api32. But it doesn't seem to work in my test

**Comment by chrisbanes** [comment]
Haze uses the surface color from `MaterialTheme` for both the blurring and scrim. I don't know what your theming is set to, but I'm guessing that the color isn't quite working. I recommend looking at the `style` parameter, or use one of the [materials](https://chrisbanes.github.io/haze/materials/) provided.
