### ISSUE TITLE
JS support request

### ISSUE THREAD

**Issue by nevrozza** [chrisbanes/haze#217]
Can you add JS support? Or just add the JS target without applying the blur effect. Thank you!

**Comment by chrisbanes** [comment]
Haze has a dependency on foundation + material3 in Compose Multiplatform, which means that we need to target WASM. If you're using Compose HTML (which can be ran in Kotlin/JS), then I recommend just using the standard CSS [backdrop-filter](https://developer.mozilla.org/en-US/docs/Web/CSS/backdrop-filter) functionality.

**Comment by chrisbanes** [comment]
As I mentioned, Haze requires Compose Foundation, which requires WASM for web support. So no, this isn't planned for Haze.
