### ISSUE TITLE
In Windows for desktope it is to freezing

### ISSUE THREAD

**Issue by skillAndroid** [chrisbanes/haze#219]
## Information

  - Haze version:
  - Platform:

## Steps to Reproduce the Problem

  1.
  1.
  1.

**Comment by chrisbanes** [comment]
I don't have a Windows machine, so I'm afraid that I have no way to confirm or fix. This library relies on Skiko so it's more likely to be a bug there.

**Comment by nevrozza** [comment]
Can you send the specs of your pc? On my laptop (i5-1235U) it works great (Windows 11) *eco mode too.

On Thursday, I want to test my app on very weak comps from my school. I'll let you know how it goes.

**Comment by chrisbanes** [comment]
Going to close this. If anyone can reproduce and provide some more information, I'm happy to take another look.
