### ISSUE TITLE
No-clipping of hazeChild Composables

### ISSUE THREAD

**Issue by seriouslyhypersonic** [chrisbanes/haze#229]
## Information

First, I would like to congratulate you on this excellent library! 

I am seriously consider using Haze in production but there is this tiny issue that is preventing me 😄 It seems haze children are not clipping as expected when their are outside the bounds of a container, which is a bit of a bummer when we need to have children on containers such as `LazyColumn` and pagers.

  - Haze version: 0.7.1
  - Platform: Android

## Expected Behavior

The `Composable` the `hazeChild` modifier is applied to is clipped when outside the bounds of a parent container and only the "visible" portion of the `hazeChild` is rendered.

## Actual Behavior

The `Composable` the `hazeChild` modifier is applied to is not clipped and suddenly "disappears" (on lazy containers) when it leaves the composition.

https://github.com/chrisbanes/haze/assets/35973158/13482f07-7f70-4e19-ac5c-281a504e03e4

## Steps to Reproduce the Problem

Here is a MRE:
```kotlin
@Composable
fun Example() {
    val hazeState = remember { HazeState() }

    Box(contentAlignment = Alignment.Center) {
        Image(
            painter = painterResource(id = R.drawable.background),
            contentDescription = null,
            modifier = Modifier
                .fillMaxSize()
                .haze(hazeState)
        )

        LazyColumn(
            modifier = Modifier
                .border(5.dp, color = Color.Green)
                .requiredSize(500.dp)
        ) {
            items(count = 30) {
                Box(
                    modifier =  Modifier
                        .padding(25.dp)
                        .fillMaxWidth()
                        .requiredHeight(100.dp)
                        .hazeChild(hazeState, style = HazeStyle(tint = Color.Red.copy(alpha = 0.3f)))
                ) {
                    Text("Haze Child $it", style = MaterialTheme.typography.displayLarge)
                }
            }
        }
    }
}
```

**Comment by chrisbanes** [comment]
I'm not entirely sure there's much we can do here. 

The way Haze works is by bypassing all of the normal top-down draw calls, and manually passing the size/position of `hazeChild` 'backwards' to some `haze` ancestor.

That works great most of the time, but as soon as you introduce draw or graphic operations in between, that kinda breaks everything.

As clipping is a draw operation set on an ancestor, the child has no idea about it. It is basically the same issue as #213

**Comment by seriouslyhypersonic** [comment]
Hum, I understand your point. This does however limit considerably the usage of Haze.

Could you be so kind and point me in the code where the size and position of the hazeChild are being passed to the haze ancestor? I would love to try and investigate the issue further and who knows, come up with a solution. I really would like to use Haze in production, but I would need to enable this use case first. Thank you!

**Comment by chrisbanes** [comment]
In fact, I think that this particular issue can be avoided by coercing the child bounds to be within the parent bounds.

Haze would have no idea whether any ancestors are using canvas clipping though, so we'd need devs to turn this coercing on/off (via a param on `hazeChild`).

**Comment by seriouslyhypersonic** [comment]
> In fact, I think that this particular issue can be avoided by coercing the child bounds to be within the parent bounds. Basically, manually clipping the areas.
> 
> Haze would have no idea whether any ancestors are using canvas clipping though, so we'd need devs to turn this coercing on/off (via a param on `hazeChild`).
> 
> I'm on vacation at the moment, but can take a look next week.

That already sounds like a promising solution! Thank you!
