### ISSUE TITLE
Alpha on background of TabRow

### ISSUE THREAD

**Issue by alirezaeiii** [chrisbanes/haze#24]
Hi Chris,

Thank you for the great library. Is it possible to set alpha on background of TabRow using your library at the moment?
https://stackoverflow.com/questions/77006590/cannot-set-alpha-for-tab-view-in-jetpack-compose

**Comment by chrisbanes** [comment]
This library will blur the content behind. Setting a transparent background on the foreground components is left as an exercise for the user.
