### ISSUE TITLE
Position sometimes gets out of sync

### ISSUE THREAD

**Issue by chrisbanes** [chrisbanes/haze#241]
> I'm not sure if it's related to this issue, but I found that sometimes when there is global position change to the parent or child, the `onPlaced` is not called and the position is not updated which causes the blur area being off.  Can we inherit `GlobalPositionAwareModifierNode` to both AndroidHazeNode and `HazeChildNode` and update the position accordingly as well?

_Originally posted by @ruishi01 in https://github.com/chrisbanes/haze/issues/213#issuecomment-2183551724_

**Comment by chrisbanes** [comment]
Yes, we could use `GlobalPositionAwareModifierNode`, but it does have a catch. `GlobalPositionAwareModifierNode` will always be called _after_ composition, meaning that any position changes will actually be applied by Haze in the next composition.

`onPlaced` etc are called as part of the layout pass, so that any changes we make should be applied with the same composition.

However, we could use `GlobalPositionAwareModifierNode` as a backup. It will basically be a no-op if layout worked correctly anyway.

**Comment by ruishi01** [comment]
@chrisbanes Sorry for the late reply, and yes, GlobalPositionAwareModifierNode will be more like a backup. Most of the time I see `onPlaced` working great placing the glaze. For some edge cases, there is position change after initial composition. 
This is the code I added for GlobalPositionAwareModifierNode:
```
override fun onGloballyPositioned(coordinates: LayoutCoordinates) {
        val newPosition = coordinates.positionInWindow() + calculateWindowOffset()
        if (area.positionOnScreen != newPosition) {
            // If there is position change after composition, update the position
            Log.i("HazeChild", "onGloballyPositioned from ${area.positionOnScreen} to $newPosition")
            area.positionOnScreen = newPosition
        }
        area.size = coordinates.size.toSize()
    }
```
I got log like this 
```
10:05:36.122 onPlaced
...
10:05:36.154 onGloballyPositioned from Offset(84.0, 1955.0) to Offset(84.0, 2277.0)
```
Can I put up a PR and add this to both `HazeChild` and `HazeAndroidNode`?

**Comment by chrisbanes** [comment]
Please do. It should be added to the `skikoMain` impl too

**Comment by kasem-sm** [comment]
Wondering if this will also be a fix #213?

**Comment by chrisbanes** [comment]
> Wondering if this will also be a fix #213?

Unlikely, as graphics layers don't affect layout (which is what Haze observes currently)

**Comment by ruishi01** [comment]
Thank you so much for the update! I will test it out in production.

**Comment by chrisbanes** [comment]
No problem, I'm planning to do a release later today.
