### ISSUE TITLE
BUILD FAILED on ios target

### ISSUE THREAD

**Issue by sppzglou** [chrisbanes/haze#243]
## Information

  - Haze version: 0.7.2
  - Platform: ios

## Expected Behavior
Expected to build on ios target. I have add the dependency on commonMain
```
commonMain.dependencies {
    implementation("dev.chrisbanes.haze:haze:0.7.2")
}
```

## Actual Behavior
Build failed on ios target, on android target build success.
<img width="1685" alt="Στιγμιότυπο οθόνης 2024-06-26, 3 05 55 μμ" src="https://github.com/chrisbanes/haze/assets/81743352/2f9c8e1d-0db1-42be-acb4-9a94bfe8cc1c">

**Comment by chrisbanes** [comment]
There is obviously not enough information here. The log you attached as a screenshot (🤨) doesn't even include the actual error. If you can find the actual error, and it is related to Haze please re-open, but for now I'm going to close this.

**Comment by sppzglou** [comment]
exactly! there is no error. Just can not compile the ios target. If I remove the implementation("dev.chrisbanes.haze:haze:0.7.2") then can compile the ios target.

**Comment by chrisbanes** [comment]
I'm afraid without the actual build error, there's nothing we can do here.
