### ISSUE TITLE
Issues with scroll

### ISSUE THREAD

**Issue by zuinqstudio** [chrisbanes/haze#245]
## Information

  - Haze version: 0.7.2
  - Platform: Kotlin - Jetpack Compose

## Expected Behavior

Applying `hazeChild` to a vertically scrollable panel should blur the content behind the panel and show without blur the content that is disclosed when scrolling

## Actual Behavior

Instead, seems that the blur is calculated "statically" so when the scroll discloses content behind (i.e. pulling down a elastic / bouncy scroll) it's still blurry even when the view that is marked with `hazeChild` is not on top of it

## Steps to Reproduce the Problem

Create a simple blur example involving a scroll:

```
Box {
    Box(modifier = Modifier.haze(state = hazeState)) {
       // Add some content like an image
    }
    Column(
        modifier = Modifier.verticalScroll(state = rememberScrollState())
    ) {
        Spacer(Modifier.height(500)) // <!-- Margin to show the scroll as kind of a bottom sheet
        Box(modifier = Modifier.hazeChild(state = hazeState, style = HazeStyle(blurRadius = 50.dp))) {
             // Add some content
        }
    }
}
```

Pulling up the scroll blurs the image behind as expected, but pulling down discloses part of the image which is still shown blurry.

PD: very nice work by the way :)

**Comment by chrisbanes** [comment]
I assume that you are running on Android here. The overscroll effect on Android is implemented (internally) as a `RenderEffect` on the scrolling container. Since Haze performs all drawing of the blurred areas in the `Modifier.haze` node, it does not participate in the overscroll effect. There's no way to observe render effects, so this is basically infeasible.

**Comment by zuinqstudio** [comment]
I see, I guess for now I'll just disable overscroll in those screens. Thanks for the clarifications :)

**Comment by chrisbanes** [comment]
I do have an idea how to fix this in the future, but it requires some Compose 1.7 APIs, and I don't even know if it will work.

**Comment by zuinqstudio** [comment]
I'm afraid my Compose skills don't reach so far (yet) to help here, but I'm happy to help with tests if you eventually find any solution. Anyway, still a minor issue, in the meantime disabling overscroll is just fine for me.
