### ISSUE TITLE
Haze Effect Disappears Over Video in Jetpack Compose; Solid Color Appears When Scrolling to Bottom

### ISSUE THREAD

**Issue by trdin** [chrisbanes/haze#249]
### Information

- **Haze version:** 0.7.2
- **Platform:** Android Kotlin - Jetpack Compose

### Expected Behavior

The Haze effect should work over videos (using ExoPlayer). The content should appear blurred when the Haze effect is applied.

### Actual Behavior

1. The Haze effect disappears when scrolling over a video.
2. When scrolling to the bottom of the screen, if the Haze effect is over a video, the area with the Haze effect is covered with a color (likely from the background).
3. The Haze effect is never present when overlaid on a video.

https://github.com/chrisbanes/haze/assets/89972475/ab15619a-977d-462a-b120-93f68f048743

### Steps to Reproduce the Problem

1. Create a top bar or any overlay with the Haze effect.
2. Place a video inside a scrollable container (or any overlay over the video).
3. Observe that the Haze effect is not present over the video.
5. Scroll to the bottom of the page while the Haze effect is over the ExoPlayer. Notice that a color appears where the Haze effect should be.

**Comment by chrisbanes** [comment]
It might work if you use a `TextureView` in ExoPlayer. By default ExoPlayer uses a SurfaceView iirc, this is never going to work.
