### ISSUE TITLE
The blur effect differences in version 0.9.0-alpha02 are quite significant.

### ISSUE THREAD

**Issue by choristery** [chrisbanes/haze#264]
## Information

  - Haze version: 0.9.0-alpha02 
  - Platform: jetpack compose

## Expected Behavior
![Screenshot_20240717_200857](https://github.com/user-attachments/assets/711c0bea-5369-4458-9ad8-05313ebe812a)

## Actual Behavior
![Screenshot_20240717_201305](https://github.com/user-attachments/assets/bf031d20-88ad-41be-991d-9d6622ad03a0)

## Steps to Reproduce the Problem

Using the same HazeStyle on version 0.7.3 and version 0.9.0 produces significantly different effects. How can we achieve the effect of `Expected Behavior` on version 0.9.0?
`
@Composable
fun hazeOverlayStyle(alpha: Float = .85f) = HazeStyle(
    blurRadius = 40.dp, tint = MaterialTheme.colorScheme.tonalSurface(1.dp).copy(alpha)
)
`

**Comment by chrisbanes** [comment]
Looks like you're missing a `backgroundColor`. See https://chrisbanes.github.io/haze/migrating-0.9/#haze-no-longer-clips-background-content

**Comment by choristery** [comment]
Thanks, it can solve the problem perfectly.
