### ISSUE TITLE
App crashing without stacktrace!

### ISSUE THREAD

**Issue by ehsannarmani** [chrisbanes/haze#276]
Hi, im trying to use the library and this is my code:
```kotlin
Box(
        modifier = Modifier
            .haze(appState.hazeState)
            .fillMaxSize()
            .statusBarsPadding()
            .imePadding()
    ) {
            Column(modifier = Modifier
                .hazeChild(
                    state = appState.hazeState,
                    shape = RoundedCornerShape(8.dp),
                    style = HazeDefaults.style(
                        backgroundColor = Red
                    ),
                )
                .fillMaxWidth()
            ) {
                Text(text = snackTitle, fontSize = 16.sp, fontWeight = FontWeight.Bold,color = Color.White)
                Text(text = snackState.currentSnackbarData?.visuals?.message.orEmpty(),color = Color.White, fontSize = 13.sp)
            }
    }
```

 But app killing proccess without any stacktrace but:
    Fatal signal 11 (SIGSEGV), code 2 (SEGV_ACCERR), fault addr 0x770225b30ee8 in tid 10310 (RenderThread), pid 10273

**Comment by ehsannarmani** [comment]
Im getting this in 0.9.0-alpha03 version
it seems its ok in 0.7.4

**Comment by chrisbanes** [comment]
This sounds like a device specific issue. What device are you using?

**Comment by chrisbanes** [comment]
Also, are you trying to use a single `HazeState` for the entire app? HazeState's should be used by exactly 1 `Modifier.haze` instance.

**Comment by ehsannarmani** [comment]
Im using it on android sdk emulator Android 14 x86_64

Yes i just used the Modifier.haze just there

**Comment by chrisbanes** [comment]
Have you reproduced this anywhere else? I can't reproduce this on any device, or the Mac arm64 emulator. Sounds like it might be an emulator issue.

**Comment by ehsannarmani** [comment]
I have the problem in A52s android 14 too
But wait, am i using correctly?
when i putting column inside a composable which have haze modifier this problem is producing
im just trying to make a composable with blurred background

**Comment by chrisbanes** [comment]
Ah no, the `haze` and `hazeChild` can not be descendants of each other. Check the samples.

> im just trying to make a composable with blurred background

"just trying" 🙄

**Comment by logickoder** [comment]
@chrisbanes can this be included in the documentation?

**Comment by chrisbanes** [comment]
I already plan on doing a full refresh of the docs to update them for 0.9.0. Even better though, we now throw an exception in this situation via #357
