### ISSUE TITLE
White artfact in round corners

### ISSUE THREAD

**Issue by Tgo1014** [chrisbanes/haze#286]
## Information

I'm trying to use haze to add some glass effect but for some reasons the corners of the tiles have some with line, it's not super noticiable in the image but you can see if you look at the corners, specially against the black background.

  - Haze version: 0.9.0-alpha04
  - Platform: Vanilla

## Expected Behavior

Corners without any white lines.

## Actual Behavior

![alt text](https://i.imgur.com/7G1yfl4.png)

## Steps to Reproduce the Problem

This is my haze child setup:

```kotlin
.hazeChild(
    state = hazeState,
    shape = RoundedCornerShape(tileSettings.cornerRadius),
    style = HazeStyle(
        backgroundColor = MaterialTheme.colorScheme.primary,
        tint = MaterialTheme.colorScheme.primary.copy(0.3f),
        blurRadius = 5.dp,
        noiseFactor = 0.09f
    ),
)
```

**Comment by chrisbanes** [comment]
What version of Android are you seeing this on?

**Comment by chrisbanes** [comment]
I'm pretty sure this has been superceded by #287. We no longer need to support shape clipping, and now leave it to the normal Compose constructs for this. Closing this.
