### ISSUE TITLE
Haze is not work

### ISSUE THREAD

**Issue by zhuhj8** [chrisbanes/haze#302]
## Due to various reasons, our project must use compileSdk 33 and Compose multiplantform 1.5.0 (not 1.6.0+). I used haze 0.4.4, which is the last version to use multiplantform 1.5.0+. Haze may not be effective due to the abandonment of some APIs or other reasons. Do you have any suggestions to solve this problem? Thank you very much

`Box(
            modifier = Modifier
                .padding(top = 16.dp)
                .fillMaxSize(),
        ) {
            Box(
                modifier = Modifier
                    .padding(bottom = 10.dp)
                    .fillMaxSize(),
            ) {
                LazyColumn(
                    state = state.listState,
                    modifier = Modifier
                        .fillMaxSize()
                        .haze(
                            state = hazeState,
                            backgroundColor = MaterialTheme.colorScheme.surface,
                        ),
                ) {
                    ......
                }
            }
            Row(
                modifier = Modifier
                    .fillMaxWidth()
                    .height(160.dp)
                    .hazeChild(state = hazeState, shape = RoundedCornerShape(24.dp))
                    .align(Alignment.BottomCenter),
                horizontalArrangement = Arrangement.Center,
                verticalAlignment = Alignment.CenterVertically,
            ) {
                .......
            }
        }`

![img_v3_02du_54f4884b-8e91-4371-9f21-85b2e869a08g](https://github.com/user-attachments/assets/5d11177f-ef6a-49b5-8afe-4a2da91ad746)

  - Haze version: 0.4.4
  - Platform: Android
  - Platform version: Android 13

## Expected Behavior
Display as white

**Comment by chrisbanes** [comment]
Unfortunately, I do not have the time to support older versions of the library.

**Comment by zhuhj8** [comment]
OK, I get it. Thank you for your contribution to this library
