### ISSUE TITLE
Android 12, SDK 31 blur not working (Samsung)

### ISSUE THREAD

**Issue by AntonAlekseevich93** [chrisbanes/haze#307]
## Information

  - Haze version: 0.7.3
  - Platform: [Android, iOS, etc] android 
  - Platform version: [Android 14, etc] - Android 12, SDK 31 

## Expected Behavior
As far as I understand, haze blur supports android 12 sdk 31, while Samsung does not have blur, although it is available on devices above. Do you have any idea what the reason might be?

**Comment by chrisbanes** [comment]
Nope #77
