### ISSUE TITLE
Default HazeStyle no more?

### ISSUE THREAD

**Issue by almozavr** [chrisbanes/haze#340]
## Information

  - Haze version: 0.9.0-beta02
  - Platform: [Android, iOS, etc]:  any
  - Platform version: [Android 14, etc]: any

## Expected Behavior
Before `0.9.0-beta02` we could apply default style to the parent `haze` element which is convenient.

## Actual Behavior
Neither `haze` nor `HazeState` accepts default `HazeStyle` anymore. Yet `HazeState` still has `var defaultStyle` that is never set though.

**Comment by chrisbanes** [comment]
Yes, explained here: https://chrisbanes.github.io/haze/migrating-0.9/#default-style-functionality-on-modifierhaze-has-been-removed

The `var defaultStyle` is a mistake and will be removed.

**Comment by almozavr** [comment]
Sorry to hear that, as now for the "defaults" we have to write own hazeChild wrapper modifier – but thanks for the clarification 🤝

**Comment by almozavr** [comment]
Thanks once more for a great explanation!

Totally agree about mutations and implicit behaviour issues – understandable why you'd want to remove the source of any instability. But let me describe my perfect flow and dev. expectations regarding the usecase we have:

1. The app has 2-3 themes with the different blur styles for each;
2. The app has 3 `haze(state)` blur sources (by z-layers) on the screen and numerous haze children;
3. Now when the app's blur config changes we need to propagate this new but global blur config across all the children;
4. My expectation/desire is:
  - if I could change the state of the blur source with the new default blur style;
  - I'm okay all the children and parent (via modifier) has to go through recomposition (it's a rare but global change anyway);
  - the default style is applied only and only if child doesn't provide own style;

Otherwise with new current API we have to create some kind of "scope" interface to keep the shared global style in and to propagate it though all the children; or to create a composition local (but then all the child modifier calls have to be `composed` or a custom node).

**Comment by chrisbanes** [comment]
I wonder if this is best implemented via a `HazeTheme` composable + composition local.

**Comment by almozavr** [comment]
the thing is if use composable approach, we can't optimize modifiers usage :( I've thought of creating own ModifierNode 

e.g.

```kotlin
class HazeChildLocalBlurStyleConsumerNode :
    DelegatingNode(),
    CompositionLocalConsumerModifierNode {

        // TODO delegate to hazeChild call with the default style of LocalHazeStyle.current
}
```

but unfortunately `HazeChildNode` is not accessible.

I believe hazeChild modifier usage should be really optimal and using `@Composable fun` to wrap the modifier call seems not the best approach we could go with.

**Comment by chrisbanes** [comment]
> unfortunately HazeChildNode is not accessible

I can make it public, there's no real reason why it is not public tbh.

**Comment by almozavr** [comment]
That would help! 

I still wonder if you could consider creating smth like 
`val LocalHazeStyle = compositionLocalWithComputedDefaultOf<HazeStyle?> { null }` and incorporate it into the `HazeChildNode` 👉👈
