### ISSUE TITLE
Blurring is thick at the bottom but thin at the top

### ISSUE THREAD

**Issue by AhmedMourad0** [chrisbanes/haze#350]
## Information

  - Haze version: 0.9.0-beta03
  - Platform: Android
  - Platform version: Android 14

## Expected Behavior
Blurring should be applied consistently to all parts of the composable similar to how it works in version 0.7.3

## Actual Behavior
Blurring is very thick toward the bottom and mid, but very thin towards the top

https://github.com/user-attachments/assets/77513157-a892-4f5d-8bc6-71a98e1229a3

## Steps to Reproduce the Problem
  Have a box composable with a `haze` list and a `hazeChild` spacer at the top in place of the status bar
  
  ```kotlin
val topInsets = WindowInsets
     .safeDrawing
     .only(WindowInsetsSides.Top)
     .getTop(density)
     .toDp(density)

Spacer(
    Modifier
         .fillMaxWidth()
         .height(topInsets)
         .hazeChild(
              state = hazeState,
              style = HazeDefaults.style(backgroundColor = Color.Transparent)
         )
)
  ```

**Comment by chrisbanes** [comment]
Working as intended as you’re setting a transparent background. Use a solid color.
