### ISSUE TITLE
Crashes with ExoPlayer

### ISSUE THREAD

**Issue by shannon-livefront** [chrisbanes/haze#351]
## Information

  - Haze version: 0.9.0-beta03
  - Platform: Android
  - Platform version: Android 14

## Expected Behavior

The video would be blurred

## Actual Behavior

The app crashes with the error `java.lang.IllegalStateException: Recording currently in progress - missing #endRecording() call?`

## Steps to Reproduce the Problem

1. Set `.haze(state = hazeState)` on an exoplayer video player view
2. Run the app

The video was blurred as expected when I changed nothing else but downgraded to version `0.7.3` of haze, so the bug seems to be related to the new `0.9.*` version only.

**Comment by chrisbanes** [comment]
Please provide a simple sample demonstrating this.

I'm surprised that ExoPlayer worked with 0.7.x to be honest. By default it uses SurfaceView, which is incompatible with Haze.

**Comment by chrisbanes** [comment]
The sample added in #356 is working great for me. I'm going to close this, but feel free to comment if the sample is missing something.
