### ISSUE TITLE
Haze 0.9.3-beta03 error effect And the blur effect of 0.7.3 is very different!

### ISSUE THREAD

**Issue by crowforkotlin** [chrisbanes/haze#353]
---------------------------------------Haze"0.9.0-beta03"---------------------------------------
```
@OptIn(ExperimentalResourceApi::class, ExperimentalHazeMaterialsApi::class)
@Composable
fun SourceScreen() {
    var hazeRadius by remember { mutableStateOf(2.dp) }
    val sources = (1..20).toList().
    LazyColumn(modifier = Modifier.fillMaxSize()) {
        items(sources.size) {
            val hazeState = remember { HazeState() }
            Box(
                modifier = Modifier
                    .padding(10.dp)
                    .fillMaxSize()
                    .border(1.dp, Color.LightGray.copy(alpha = 0.5f), RoundedCornerShape(7.5.dp))
                    .shadow(1.dp, RoundedCornerShape(7.5.dp))
                    .background(MaterialTheme.colorScheme.primary)
                    .hazeChild(
                        state = hazeState,
                    ) {
                        applyStyle(HazeStyle(backgroundColor = Color.Yellow, tint = null, blurRadius = 3.dp))
                        mask = Brush.linearGradient(listOf(Color.Black, Color.Black))
                    },
            ) {
                Row(
                    modifier =
                    Modifier.haze(hazeState)
                ) {
                    Icon(
                        imageVector = Icons.Rounded.Create,
                        contentDescription = null,
                        modifier = Modifier.padding(10.dp)
                    )
                    Text(
                        text = sources[it].toString(),
                        style = MaterialTheme.typography.bodyLarge.copy(fontWeight = FontWeight.Medium),
                        modifier = Modifier.padding(10.dp)

                    )
                }
            }
        }
    }
}
```

![error effect](https://github.com/user-attachments/assets/c87dfa5f-36b0-4951-981f-17c9c820d65b)

https://github.com/user-attachments/assets/409d81cf-30f2-44d5-a02a-4388f20ab351

---------------------------------------Haze"0.9.0-beta03"---------------------------------------

Haze's Blur effect was excellent with the Haze 0.7.3 implementation, but in 0.9.0-beta03 I no longer know how to implement it, and it comes with the error effect

And the only problem that existed with Haze 0.7.3 was the native ptr null #352 that I gave feedback on earlier, which was indeed solved in 0.9.0-beta03, but the problem was as I described above

**Comment by chrisbanes** [comment]
You're setting the modifiers are descendants of each other. 

HazeChild and Haze cannot be decedents of each other. That has always been the case.

Check the samples: https://github.com/chrisbanes/haze/tree/main/sample/shared/src/commonMain/kotlin/dev/chrisbanes/haze/sample

**Comment by crowforkotlin** [comment]
> You're setting the modifiers as descendants of each other.
> 
> HazeChild and Haze cannot be descendants of each other, as one would draw the other. That has always been the case.
> 
> Check the samples: https://github.com/chrisbanes/haze/tree/main/sample/shared/src/commonMain/kotlin/dev/chrisbanes/haze/sample

Ok, thanks, I looked at the sample of 0.9.0 and carefully debugged step by step to finally achieve the result
