### ISSUE TITLE
Blurred content offset since Beta04

### ISSUE THREAD

**Issue by harry248** [chrisbanes/haze#367]
## Information

  - Haze version: 0.9.0-beta04, 0.9.0-beta04.1
  - Platform: Android, iOS
  - Platform version: Android 15

## Expected Behavior

Content isn't offset

## Actual Behavior

The blurred content is strangely shifted on the x axis. See screenshots (second one is using 0.9.0-beta04)

## Steps to Reproduce the Problem

  1. Use any version after 0.9.0-beta03

<img width="507" alt="beta03" src="https://github.com/user-attachments/assets/96de12fa-dc65-4ac9-b4b6-245f1c5a9d52">
<img width="507" alt="beta04" src="https://github.com/user-attachments/assets/0583d1f7-2529-4ef3-8712-f1cfda9e5c59">

**Comment by chrisbanes** [comment]
I can't recreate this. If you turn the blurRadius down to `0.dp` what does it look like?

**Comment by harry248** [comment]
@chrisbanes There is actually no offset when I set the `blurRadius` to `0.dp`. The offset correlates with the `blurRadius` - the larger this is, the larger the negative offset becomes.

**Comment by chrisbanes** [comment]
Interesting. I'm still not seeing that though 🤔

Just double checking, are you sure that you're using `0.9.0-beta04.1`? That has a fix for blurRadius from styles not working.

**Comment by harry248** [comment]
I am using `0.9.0-beta04.1` and also tried `0.9.0-beta04`. The last version the issue didn't occur was `0.9.0-beta03`.

**Comment by chrisbanes** [comment]
Can you post some code of how you're using Haze? Maybe there's something which I'm missing.

**Comment by chrisbanes** [comment]
I still can't recreate this unfortunately. If anyone else can reproduce this, please comment/react (ideally with an example).

**Comment by rosuH** [comment]
I encountered a similar problem (Unsure if causes match. Commenting here first. Will create new issue if needed). I used 'hazeChild` for `PrimaryScrollableTabRow`. From the video, you can see that there is blurring effect even before scrolling.

Removing `statusBarsPadding()` doesn't seem to help.

https://github.com/user-attachments/assets/3ad772e1-d7f0-4891-86fb-65066a792d27

## Code snippet:

```kt
@OptIn(ExperimentalMaterial3Api::class)
@Composable
@Preview
fun App() {
    MaterialTheme {
        var showContent by remember { mutableStateOf(false) }
        Column(modifier = Modifier.fillMaxSize()) {
            var tabState by remember { mutableStateOf(0) }
            val titles = listOf("Article", "Social Media", "Image", "Video", "Audio", "Notification")
            val coroutineScope = rememberCoroutineScope()
            val pagerState = rememberPagerState(pageCount = {
                titles.size
            })
            val hazeState = remember { HazeState() }
            LaunchedEffect(pagerState) {
                snapshotFlow { pagerState.currentPage }.collect { page ->
                    tabState = page
                }
            }
            PrimaryScrollableTabRow(
                modifier = Modifier.hazeChild(
                    hazeState,
                    style = HazeMaterials.thin(MaterialTheme.colorScheme.background)
                ),
                containerColor = Color.Transparent,
                selectedTabIndex = tabState,
                edgePadding = 8.dp,
                divider = {}
            ) {
                titles.forEachIndexed { index, title ->
                    Tab(
                        selected = tabState == index,
                        onClick = {
                            tabState = index
                            coroutineScope.launch {
                                pagerState.animateScrollToPage(index)
                            }
                        },
                        text = {
                            if (tabState == index) {
                                Text(
                                    text = title,
                                    maxLines = 2,
                                    overflow = TextOverflow.Ellipsis,
                                    style = MaterialTheme.typography.titleMedium,
                                    fontWeight = FontWeight.Bold
                                )
                            } else {
                                Text(
                                    text = title,
                                    maxLines = 2,
                                    overflow = TextOverflow.Ellipsis,
                                    color = MaterialTheme.colorScheme.onSurfaceVariant,
                                    style = MaterialTheme.typography.titleSmall
                                )
                            }
                        }
                    )
                }
            }
            HorizontalPager(modifier = Modifier.haze(state = hazeState).fillMaxSize(), state = pagerState) { page ->
                DemoListScreen(titles[page])
            }
        }

    }
}

@Composable
fun DemoListScreen(title: String) {
    LazyColumn(
        modifier = Modifier.fillMaxSize(),
        horizontalAlignment = Alignment.CenterHorizontally
    ) {
        repeat(100) {
            item {
                Button(onClick = { /*TODO*/ }, modifier = Modifier.fillMaxWidth().padding(8.dp)) {
                    Text(text = "$title  Item $it", style = MaterialTheme.typography.titleLarge)
                }
            }
        }
    }
}

```

#### project for reproduction https://github.com/rosuH/haze-reproduced

**Comment by chrisbanes** [comment]
Hi, please don't comment on closed issues, even if you think it is related.

As to your sample, it's make little sense. You're using a `Column`, so the tab bar isn't being drawn on top of the `HorizontalPager`. Without that, Haze is useless as the whole point is background blurring.

Use a `Scaffold` instead and it works as expected. Related sample is here: https://github.com/chrisbanes/haze/blob/main/sample/shared/src/commonMain/kotlin/dev/chrisbanes/haze/sample/ScaffoldSample.kt
