### ISSUE TITLE
Artifact when use slide animation

### ISSUE THREAD

**Issue by nevrozza** [chrisbanes/haze#371]
## Information

  - Haze version: 0.9.0-rc01
  - Platform: JVM (macOS)
  - Platform version: Sonoma

## Expected Behavior
HazeArea goes with sliding screen

## Actual Behavior
Haze makes artifact (video)

I use decompose and his transition (iosSlide() + fade()). When i use only fade() it work great. But when i'm trying to use haze with slide() it goes like on video. (There is a sample with HazeProgressive, without it'll be just spot)

**Comment by nevrozza** [comment]
https://github.com/user-attachments/assets/b4edc179-2d90-4a87-81ee-63dddc3dfcaf

**Comment by chrisbanes** [comment]
This looks similar to #367

**Comment by chrisbanes** [comment]
I can't recreate this, and there's not enough information here to proceed.

**Comment by chrisbanes** [comment]
Please give 0.9.0-rc02 a try. I'm 70% sure that this will fix it.

**Comment by nevrozza** [comment]
> Please give 0.9.0-rc02 a try. I'm 70% sure that this will fix it.

Yes, Now it works perfect. Thanks! You're the best!
