### ISSUE TITLE
I got Layout nodes using Modifier.haze and Modifier.hazeChild can not be descendants of each other error after upgrade to 1.0.0

### ISSUE THREAD

**Issue by ti4n1993** [chrisbanes/haze#394]
I blur the app bar and the bottom navigation bar, and blur the sensitive information in the list below the app bar and the bottom navigation bar

**Comment by chrisbanes** [comment]
The error says what the problem is.

I don’t understand why you’ve raised an issue? If you think the error is a false-positive, then please attached some code.

**Comment by ti4n1993** [comment]
Sorry, it's my code error
