### ISSUE TITLE
How use with ExoPlayer?

### ISSUE THREAD

**Issue by Evrixand** [chrisbanes/haze#403]
## Information

  - Haze version:
  - Platform: [Android, iOS, etc]
  - Platform version: [Android 14, etc]

## Steps to Reproduce the Problem

  1.
  1.
  1.

**Comment by chrisbanes** [comment]
The search function on GitHub works well.

https://github.com/chrisbanes/haze/blob/main/sample/android/src/main/kotlin/dev/chrisbanes/haze/sample/android/ExoPlayerSample.kt
