### ISSUE TITLE
Broken link in 1.0 migration guide

### ISSUE THREAD

**Issue by alsutton** [chrisbanes/haze#407]
The link in the [section on style functionality](https://chrisbanes.github.io/haze/migrating-1.0/#default-style-functionality-on-modifierhaze-has-been-moved) for `LocalHazeStyle` goes to `https://chrisbanes.github.io/haze/migrating-1.0/api/haze/dev.chrisbanes.haze/-local-haze-style.html` when it should point to `https://chrisbanes.github.io/haze/api/haze/dev.chrisbanes.haze/-local-haze-style.html` (without the `migrating-1.0/` section)

**Comment by chrisbanes** [comment]
Thanks for the report, fixed and deploy in progress!
