### ISSUE TITLE
TopAppBar Transparent

### ISSUE THREAD

**Issue by DatL4g** [chrisbanes/haze#411]
## Information

  - Haze version: 1.0.2
  - Platform: Android

I am using Haze on my TopAppBar, the blur effect works as expected but the container color behaves a bit weird.
The screenshots below show the results between different `HazeMaterials.thin()` container colors.

The expected behavior is equals the result from haze `0.7.3`, I know there was a huge internal change in `0.9.0` so I just want to check back if this behavior is correct.

The container is always a bit dark tinted, when using default container color or `Color.Transparent`.
 
## Expected Behavior

Result using haze `0.7.3` with default container color

| Expanded | Collapsed |
|:---:|:---:|
| ![Screenshot_20241115_232337](https://github.com/user-attachments/assets/12948f7e-65e1-4670-9666-a9c49854a4cc) | ![Screenshot_20241115_232401](https://github.com/user-attachments/assets/6bb6cf78-8d79-4de2-b7d9-b033ad1b698e) |

## Default Container Color

Using `HazeMaterials.thin()` as style

| Expanded | Collapsed |
|:---:|:---:|
| ![Screenshot_20241115_232629](https://github.com/user-attachments/assets/5d8fcc06-ce52-484b-8d06-b39103207726) | ![Screenshot_20241115_232401](https://github.com/user-attachments/assets/e786f808-0704-407e-a95a-76b643ae7628) |

## Color Container Transparent

Using `HazeMaterials.thin(Color.Transparent)` as style

| Expanded | Collapsed |
|:---:|:---:|
| ![Screenshot_20241115_232715](https://github.com/user-attachments/assets/d396055b-6777-4bc2-a2bc-a91d8b3c423f) | ![Screenshot_20241115_232729](https://github.com/user-attachments/assets/b4ac1b56-d188-403f-ba77-6a895a6ac631) |

My Collapsing TopAppBar (to add this background image) looks like this:

```kotlin
Box(
        modifier = Modifier.fillMaxWidth()
    ) {
        val collapseState by remember(state) {
            derivedStateOf {
                CollapsingToolbarState(
                    expandProgress = max(min(1F - state.collapsedFraction, 1F), 0F)
                )
            }
        }

        background(collapseState)
        LargeTopAppBar(
            navigationIcon = {
                navigationIcon(collapseState)
            },
            title = {
                title(collapseState)
            },
            actions = {
                actions(collapseState)
            },
            scrollBehavior = scrollBehavior,
            colors = TopAppBarDefaults.largeTopAppBarColors(
                containerColor = Color.Transparent,
                scrolledContainerColor = Color.Transparent
            ),
            modifier = modifier
        )
    }
```

My workaround to achieve the old behavior is this:

```kotlin
fun Modifier.hazeChild(
    state: HazeState = LocalHaze.current,
    style: HazeStyle = HazeMaterials.thin(),
    listState: LazyListState
) = Modifier.hazeChild(
    state = state,
    style = style
) {
    alpha = if (listState.firstVisibleItemIndex == 0 && listState.firstVisibleItemScrollOffset == 0) {
        0F
    } else {
        1F
    }
}
```

**Comment by chrisbanes** [comment]
This is working as intended, due to https://chrisbanes.github.io/haze/migrating-1.0/#haze-no-longer-clips-background-content.

> The container is always a bit dark tinted

That's controlled by the `tint`, not `backgroundColor`.  You might want to change the tint alpha, rather than the `alpha` of the entire effect.
