### ISSUE TITLE
Haze Occasionally Renders Transparent Background in Composable

### ISSUE THREAD

**Issue by iZakirSheikh** [chrisbanes/haze#420]
## Information

  - Haze version: 1.0.2
  - Android version: 13

## Expected Behaviour
 Occasionally, Haze fails to blur the component, displaying a transparent background instead.

## Steps to Reproduce the Problem
Here is the link to my app: [Audiofy](https://play.google.com/store/apps/details?id=com.prime.player&pli=1). The issue arises intermittently, and the cause is not clear. You can verify this by examining the app yourself. The problem manifests on the primary screen, specifically within the top composable of the BottomNavBar in the Home Composable. I believe this occurs because the BottomNavBar gets detached on some screens; after reattaching, sometimes the background is not blurred.
Github - https://github.com/iZakirSheikh/Audiofy

### Request
Would it be possible for you to mention in your introduction of the library that the app called Audiofy also utilizes it?
Thank you.

**Comment by chrisbanes** [comment]
I'm afraid that I'm not going to go debugging your app. If you can provide a _simple_ reproducible sample then I'll take a look.

**Comment by iZakirSheikh** [comment]
> I'm afraid that I'm not going to go debugging your app. If you can provide a _simple_ reproducible sample then I'll take a look.
 - This happens when BottomNavBar re-imerges after hiding in some screens

**Comment by merahulroshan** [comment]
@iZakirSheikh I am having the same issue, did you found the solution?
