### ISSUE TITLE
LazyList Sticky headers

### ISSUE THREAD

**Issue by Skaldebane** [chrisbanes/haze#425]
Hi! I've recently come across an interesting use-case:

One of my apps' main screen is a `LazyColumn` with a bunch of `stickyHeader`s, and I'd like to make the sticky headers' background blurred using haze (blurring the _other_ regular items that are scrolling underneath it).

Of course this wouldn't work out of the box by applying the `haze` modifier to the `LazyColumn` itself, as the sticky headers with `blurChild` are inside it.

And there's no way to group all of the non-sticky list items under a single `haze` modifier that is on the same level as the sticky headers, so I guess this is currently simply impossible?

I tried making the actual sticky headers just transparent dummies, and overlaying my own based on their positions... but it's quite janky, with visual overlaps and slight delays when scrolling rapidly.

Was also wondering if I could somehow make it work by creating a custom lazy layout, but I'm not sure if that changes anything either.

What do you think? Is this feasible somehow? It's nothing critical, but it's an interesting use case for sure.

**Comment by chrisbanes** [comment]
> I tried making the actual sticky headers just transparent dummies, and overlaying my own based on their positions... but it's quite janky, with visual overlaps and slight delays when scrolling rapidly.

Yeah this is likely going to be the only (easy) way right now.

> Was also wondering if I could somehow make it work by creating a custom lazy layout

This will work, but it's a lot of work.

--- 

I do have an idea of how we could enable this kind of scenario. The idea being that you can actually attach multiple `Modifier.haze` nodes to the HazeState.

The usage would look a bit like this:

``` kotlin
val hazeState = remember { HazeState() }

LazyColumn(...) {
    stickyHeader {
        Foo(Modifier.hazeChild(hazeState))
    }

    items(list) { item ->
        Bar(
            item,
            Modifier.haze(hazeState)
        )
    }
}
```

**Comment by Skaldebane** [comment]
I thought of that too! It would be pretty nice, where all of those items get merged into one big surface (graphics layer? not familiar with the terminology) used for the blur, right?

But I'm wondering if there could be any performance drawbacks to doing this? ..particularly when applied to tens of items in a grid?

**Comment by Skaldebane** [comment]
Here's a screenshot from the app. It's a pretty dense grid, so can get to 100s of cards on the screen at once on large screens.

![screenshot](https://github.com/user-attachments/assets/3f0866c9-1a85-4e3a-8dc3-e2e0356387a9)
