### ISSUE TITLE
The same 'unique_name=kotlin' found in more than one library:

### ISSUE THREAD

**Issue by liuhongjian0316** [chrisbanes/haze#426]
- Haze version:1.0.2
  - Platform:  wasm 
  - kotlin = "2.1.0"

------------
KLIB resolver: The same 'unique_name=kotlin' found in more than one library: /Users/liuhongjian/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-stdlib-wasm-js/2.1.0/b96271506fb37f4d8d1c63db7a57384ab16ae218/kotlin-stdlib-wasm-js-2.1.0.klib, /Users/liuhongjian/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-stdlib-wasm/1.9.10/834185c1765a20be76d8ffb6eeecf2b0068baf61/kotlin-stdlib-wasm-1.9.10.klib
Please file an issue to https://kotl.in/issue and meanwhile use CLI flag `-Xklib-duplicated-unique-name-strategy` with one of the following values:
allow-all-with-warning: Use all KLIB dependencies, even when they have same `unique_name` property.
allow-first-with-warning: Use the first KLIB dependency with clashing `unique_name` property. No order guarantees are given though.
deny: Fail a compilation with the error.

**Comment by chrisbanes** [comment]
I don't see anything to do with Haze in that log. I'm not sure why you've raised an issue here? The log message tells you what to do.
