### ISSUE TITLE
Feature request: ability to animate the opacity of the blur

### ISSUE THREAD

**Issue by alexRocket891** [chrisbanes/haze#434]
## Information

  - Haze version: 1.1.1
  - Platform: [Android]
  - Platform version: [Android 14]

## Expected Behavior
In our project we use Haze as a blur overlay behind a loading animation, which covers the entire screen. As a new feature, it would be great to be able to use AnimateVisibility, or similar solutions to smoothen the appearance and disappearance of the blur layer.

## Actual Behavior
Currently using AnimateVisibility, or alpha animation can lead to the blur to not load/become visible, or disappear in a fraction of a second then reappear for like 10-20ms just before the animation would end.

## Steps to Reproduce the Problem

  1. Create a project with a simple screen and a button
  2. Create a composable that overlays the entire screen as a loading
  3. Apply haze to the main screen, apply hazechild to the overlay
  4. Use the button to toggle a flag, the flag should control the AnimateVisibility(visible = toggle, enter = fadeIn(), exit= fadeOut())
  
  ```
val compatHaze = compatHaze()
  AnimatedVisibility(
                visible = showLoading,
                enter = fadeIn(),
                exit = fadeOut(),
            ) {
            Column(
            modifier =
            modifier
                . hazeChild(state = hazeState, style = compatHaze) {
                        backgroundColor = background
                    }
                    .fillMaxSize(),
        ) {
        // Loading indicator
            }
```
            
Since the original blur value was way too strong for us, I created an alternative style:

```
@ExperimentalHazeMaterialsApi
@Composable
@ReadOnlyComposable
fun compatHaze(
    containerColor: Color,
): HazeStyle = customHazeMaterial(
    containerColor = containerColor,
    lightAlpha = if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.S) 0.65f else 0.75f,
    darkAlpha = if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.S) 0.5f else 0.75f,
)

private fun customHazeMaterial(
    containerColor: Color,
    lightAlpha: Float,
    darkAlpha: Float,
): HazeStyle = HazeStyle(
    blurRadius = 3.dp,
    backgroundColor = containerColor,
    tint = HazeTint(
        containerColor.copy(alpha = if (containerColor.luminance() >= 0.5) lightAlpha else darkAlpha),
    ),
)
```

**Comment by chrisbanes** [comment]
This already exists, use the `alpha` property on the scope:

``` kotlin
val animatedAlpha by animateFloatAsState(...)

Foo(
    modifier = modifier.hazeChild(state = hazeState) {
      alpha = animatedAlpha
    }
)
```

**Comment by chrisbanes** [comment]
As to the issues with `AnimatedVisibility`, I can't reproduce unfortunately.

https://github.com/user-attachments/assets/e5d26b29-d20c-4e6b-b693-6686a8b4a3d0

**Comment by alexRocket891** [comment]
Thanks, I will try the alpha, and will also dig deeper into the AnimateVisibility issue.

**Comment by chrisbanes** [comment]
👍 sounds good. Ping here if you find an issue

**Comment by alexRocket891** [comment]
The alpha setting works great, I apologize for missing it, as for the AnimateVisibility, right now the alpha produces a much better result so we will keep using that. Thank you again!
