### ISSUE TITLE
Support for drawWithContent

### ISSUE THREAD

**Issue by marcelskotnicki** [chrisbanes/haze#435]
## Information
  - Haze version: 1.0.2
  - Platform: Android
  - Platform version: Android 13

## Expected Behavior
Is it possible to make haze work with `.drawWithContent { .. }`? 
Currently, when `.hazeChild(..)` is called after `.drawWithContent { .. }` nothing happens. 

## Example
```
    Box(
        modifier = modifier
            .matchParentSize()
            .drawWithContent {
                val cutoutRect = cutout.calculateCutoutRect(
                    density = density,
                    parentSize = this.size,
                )
                val cornerRadius = with(density) {
                    cornerRadiusSize.toPx()
                }
                val roundRectPath = Path().apply {
                    addRoundRect(
                        roundRect = RoundRect(
                            rect = cutoutRect,
                            radiusX = cornerRadius,
                            radiusY = cornerRadius,
                        ),
                    )
                }
                clipPath(roundRectPath, clipOp = ClipOp.Difference) {
                    drawRect(color = color)
                }
            }
            .hazeChild(state = hazeState) {
                backgroundColor = Color.Transparent
                tints = listOf(HazeTint(tint))
                fallbackTint = HazeTint(fallbackColor)
                blurRadius = 32.dp
                noiseFactor = 0f
            },
    )
```
But when I call `.hazeChild(..)` before `.drawWithContent { .. }` it works properly, but blurs whole screen.

**Comment by chrisbanes** [comment]
What are you actually trying to achieve here? Because you're using `drawWithContent` but not actually calling `drawContent()`?

**Comment by marcelskotnicki** [comment]
In my example, I try to blur the outside part of the cutout (hence clip difference).
![ss](https://github.com/user-attachments/assets/9d283453-b4c0-4312-bd25-8759279ca68a)

**Comment by chrisbanes** [comment]
Yes, I think you're missing a call to `drawContent()`.

**Comment by marcelskotnicki** [comment]
@chrisbanes Unfortunately, calling `drawContent()` after `clipPath(..)` only caused the whole screen to get blurred and overlay to not be drawn.

**Comment by marcelskotnicki** [comment]
![image](https://github.com/user-attachments/assets/c17397c6-e6a5-49f4-b6e3-a62875da1b9f)

**Comment by chrisbanes** [comment]
Works for me:

<img src="https://github.com/user-attachments/assets/6263091e-2e3b-4f64-b965-95dccafd7ac9" width=300>

``` kotlin
Box(
  modifier = Modifier
    .fillMaxSize()
    .drawWithContent {
      val roundRectPath = Path().apply {
        // ...
      }
      clipPath(roundRectPath, clipOp = ClipOp.Difference) {
        this@drawWithContent.drawContent()
      }
    }
    .hazeChild(state = hazeState),
) {
  // ...
}
```
