### ISSUE TITLE
Blur only images

### ISSUE THREAD

**Issue by sppzglou** [chrisbanes/haze#445]
## Information

  - Haze version:
  - Platform: [Android, iOS, multiplatform]

In version 1.1.1 the blur is only on the images and not in other views like texts.

[Screen_recording_20241215_160631.webm](https://github.com/user-attachments/assets/e89199bf-dfdc-4968-974e-7e6d361174ed)

**Comment by chrisbanes** [comment]
Am I supposed to imagine what your code looks like?

This is almost certainly because you're not providing a backgroundColor in the HazeStyle.
