### ISSUE TITLE
Regular blur work incorrencly on edges of screen

### ISSUE THREAD

**Issue by XantreDev** [chrisbanes/haze#460]
## Information

  - Haze version:1.1.1
  - Platform: Android
  - Platform version: Android 15

## Expected Behavior
Blur edges with some effect (Mirror is ideal)

## Actual Behavior
Regular blur:
```kotlin
    Box(
        modifier =
            Modifier.align(Alignment.TopCenter)
                .fillMaxWidth()
                .height(paddingValues.calculateTopPadding())
                .hazeChild(
                    hazeState,
                ) {
//                  progressive =
//                      dev.chrisbanes.haze.HazeProgressive.verticalGradient(
//                          startIntensity = 1f, endIntensity = 1f)
                  style =
                      HazeStyle(
                          backgroundColor = Color.Transparent,
                          blurRadius = 30.dp,
                          tint = HazeTint(Color.LightGray.copy(alpha = 0.3f)))
                })
```
![image](https://github.com/user-attachments/assets/7e8faba2-4175-4024-9742-a03fbb9a0619)

progressive 1 to 1
![image](https://github.com/user-attachments/assets/4935b5cc-e56e-4e33-b360-4f61d040b796)

```kotlin
    Box(
        modifier =
            Modifier.align(Alignment.TopCenter)
                .fillMaxWidth()
                .height(paddingValues.calculateTopPadding())
                .hazeChild(
                    hazeState,
                ) {
                  progressive =
                      dev.chrisbanes.haze.HazeProgressive.verticalGradient(
                          startIntensity = 1f, endIntensity = 1f)
                  style =
                      HazeStyle(
                          backgroundColor = Color.Transparent,
                          blurRadius = 30.dp,
                          tint = HazeTint(Color.LightGray.copy(alpha = 0.3f)))
                })
```

## Steps to Reproduce the Problem

Use regular blur as background of top bar

**Comment by chrisbanes** [comment]
Use search for why I've closed this.

**Comment by chrisbanes** [comment]
(hint: look at the background color)

**Comment by marcelskotnicki** [comment]
@chrisbanes Sorry, I've searched through multiple issues, but still couldn't find the answer. After setting `backgroundColor` to `Transparent` the screen's edges are not blurred, but setting some solid color is not the answer though. How can we achieve fullscreen, edge-to-edge blur?

**Comment by chrisbanes** [comment]
Setting an opaque background color is the answer.

**Comment by marcelskotnicki** [comment]
So there is no way to achieve fullscreen blur 😕 Not complaining tho, the lib is perfect 👌

**Comment by chrisbanes** [comment]
What is 'fullscreen blur'?

**Comment by marcelskotnicki** [comment]
From edge to edge, from status bar to navigation bar, without fading away. Here's another example
```
            .hazeChild(state = hazeState) {
                backgroundColor = Color.Transparent
                fallbackTint = HazeTint(fallbackColor)
                blurRadius = 20.dp
                noiseFactor = 0f
            }
```
![Screenshot_20241228_101419](https://github.com/user-attachments/assets/cc9cbf1d-3582-40ce-9540-3764c4b1884e)

**Comment by chrisbanes** [comment]
Just try an opaque colour, as I've said a few times now.

**Comment by marcelskotnicki** [comment]
Sure, I understood the first time 👍 But imho setting an opaque color it is not the answer, when system bars are transparent (edge-to-edge) you simply don’t want to color them. Additionally, in my example I blur camera preview, so there is no background of the content. I’ve set the background color to black, so it fills the gap and gradients to device bezels, but it’s rather a workaround not solution.
