### ISSUE TITLE
 uses-sdk:minSdkVersion 21 cannot be smaller than version 24 declared in library 

### ISSUE THREAD

**Issue by gybin02** [chrisbanes/haze#60]
Manifest merger failed : uses-sdk:minSdkVersion 21 cannot be smaller than version 24 declared in library [dev.chrisbanes.haze:haze-jetpack-compose:0.4.1] /Users/yd-sz-dn0588/.gradle/caches/transforms-3/b2ddb0cf5d948a8541195c91900041ce/transformed/haze-jetpack-compose-0.4.1/AndroidManifest.xml as the library might be using APIs not available in 21
	Suggestion: use a compatible library with a minSdk of at most 21,
		or increase this project's minSdk version to at least 24,
		or use tools:overrideLibrary="dev.chrisbanes.haze.jetpackcompose" to force usage (may lead to runtime failures)

**Comment by chrisbanes** [comment]
Your project is using a minSdk of 21, and Haze needs 24. We may be able to drop it lower, but it's not really an issue with the library itself.

**Comment by chrisbanes** [comment]
Fixed by #61

**Comment by gybin02** [comment]
You're so good at achieving version compatibility so quickly
