### ISSUE TITLE
Optional tint?

### ISSUE THREAD

**Issue by poliver** [chrisbanes/haze#69]
Supplying a transparent tint crashes (due to lack of alpha, I'm guessing?), so I'm currently supplying white with the lowest possible alpha value to achieve the effect I want (as close as I can).

My use case is a hazy bottom bar in a scaffold. Screens slide in and out of the scaffold. I'm animating the bottom bar to slide off screen when it's conditionally hidden. When a screen containing a haze child (scrollable content) slide-exits the scaffold while simultaneously hiding the bottom bar, the tint, although visually belonging to the bottom bar, can be sliding away with the exiting content. If tint were absent, I could just set a translucent background on the bottom bar. Was there a reason for requiring tint?

**Comment by chrisbanes** [comment]
Can you please provide more information:

- Haze version (and artifact if on Android)
- Platform

I've just tried a `Color.Transparent` tint with Haze 0.4.1 on Desktop and Android (`haze` and `haze-jetpack-compose`) and everything worked as expected.

**Comment by poliver** [comment]
This is on Android using `haze-jetpack-compose:0.4.1`.

```
java.lang.IllegalArgumentException: nativePtr is null
	at libcore.util.NativeAllocationRegistry.registerNativeAllocation(NativeAllocationRegistry.java:264)
	at android.graphics.RenderEffect.<init>(RenderEffect.java:314)
	at android.graphics.RenderEffect.createColorFilterEffect(RenderEffect.java:204)
	at dev.chrisbanes.haze.HazeNode31.buildEffects(HazeNode31.kt:179)
	at dev.chrisbanes.haze.HazeNode31.access$buildEffects(HazeNode31.kt:50)
	at dev.chrisbanes.haze.HazeNode31$draw$3.invoke(HazeNode31.kt:130)
	at dev.chrisbanes.haze.HazeNode31$draw$3.invoke(HazeNode31.kt:129)
```

**Comment by poliver** [comment]
```
LazyVerticalGrid(
    modifier =
      modifier
        .fillMaxSize()
        .haze(
          state = hazeState,
          backgroundColor = MaterialTheme.colorScheme.background,
          tint = Color.Transparent,
          blurRadius = 4.dp
        ),
. . .
```

paired with

```
BottomBar(
  modifier =
    Modifier.hazeChild(hazeState)
      .background(color = MaterialTheme.colorScheme.surfaceVariant)
```

**Comment by chrisbanes** [comment]
Ah just managed to recreate this on an API 31 emulator. It works on API 34 so looks like a framework bug. Easy to workaround though.

**Comment by poliver** [comment]
Thanks for the fix @chrisbanes! I still wonder why tint needs to default to a non-transparent/non-null value when it doesn't appear necessary to achieve the blur effect (like `backgroundColor` is). It's a nice option, but I personally think it's more intuitive to set a translucent background on the haze child (also visible in previews). Is it more performant to tint while rendering the blur?

**Comment by chrisbanes** [comment]
The default is a translucent colour because you tend to need it when displaying any foreground content on top, and maintain contrast.

Of course, this is a generalisation so if you don't for your use case you are free to change it as required.

Tbh I'd like to get rid of the `backgroundColor` parameter as it's a hack. I think we can implement it in a better way (repeat the outer pixels), but I'm now sure if it's technically possible on all platforms.

**Comment by poliver** [comment]
> The default is a translucent colour because you tend to need it when displaying any foreground content on top, and maintain contrast.

I understand, but this also implies that the haze child must set a fully transparent bg color, doesn't it? It seems counterintuitive to colocate the content scrim/contrast with the blur layer and not the content, itself.

Defaulting haze tint to transparent (or removing it altogether) lets the haze children specify their own translucent bg, with the added advantage of being visible in previews.

**Comment by chrisbanes** [comment]
Ah I see what you're saying. Using the tint in the blur effect has a slightly different effect than setting a background colour, especially on iOS/Desktop where it is used directly in the runtime shader. It also makes handling the `shape` easier, otherwise you'd have to set the background shape too.

Again though, you have the option to do what you want. The default options are there to implement the most common use case with minimal work.

**Comment by poliver** [comment]
> Using the tint in the blur effect has a slightly different effect than setting a background colour

Ah ok, I wasn't sure if it was because of something like this. Thanks for the clarification.
