### ISSUE TITLE
Blur doesn't follow Dialog on Android 33

### ISSUE THREAD

**Issue by poliver** [chrisbanes/haze#86]
Not sure if this is due to Dialog window, but when displaying a compose `Dialog` containing a `Surface`, the haze doesn't follow the dialog, but remains frozen in the top left corner of the screen. `.hazeChild()` is set on the `Surface`.

**Comment by poliver** [comment]
https://github.com/poliver/HazeDialogRepro

<img src="https://github.com/chrisbanes/haze/assets/3497406/f0f15251-27c5-4d54-b1e1-d764a5dc8517" width=200>

**Comment by chrisbanes** [comment]
Thanks!

**Comment by chrisbanes** [comment]
Just had a quick look into this. So we map all `hazeChild` positions using `positionInRoot` (root being the root composable), which is the simplest way to handle this 95% of the time. `Dialog`s however are put into their own `android.view.Window` on Android, which means that they're not part of the original root composable. They have their own root composable, with its content being displayed at `0,0`, hence why the blurring is at the top left.

To fix this we need to calculate everything in 'screen' coordinates, by passing along the window offset when sending the `hazeChild` positions. That's not particularly difficult, but we need to do it in a way which works across platforms, which is probably going to be trickier.
