### ISSUE TITLE
Paparazzi Snapshot tests failing between 0.4.1 -> 0.4.2

### ISSUE THREAD

**Issue by wezley98** [chrisbanes/haze#87]
As title, we integrated haze into our project at 0.4.1, but any version above 0.4.2/0.4.3/0.4.4 doesn't show the haze in our snapshots anymore.

0.4.4 Delta
-------------
![delta-com sky sport group snapshots components_CarouselListComponentSnapshotTest_testCarouselListComponent NEXUS_5,1 0,10 Tile(layout=Hero, images=Images(sixt ,Light](https://github.com/chrisbanes/haze/assets/1488209/a69ac7df-5ac6-484d-9648-15069cf7f95a)

Example Usage
-----------
```
Box(modifier = Modifier.clip(RoundedCornerShape(8.dp))) {
            val imageSizeModifier = Modifier
                .aspectRatio(ratio = AspectRatio.FOUR_BY_THREE.ratio)

            val hazeState = remember { HazeState() }

            UrlImage(
                modifier = imageSizeModifier.then(
                    if (tile.containsVideo) {
                        Modifier.haze(
                            state = hazeState,
                            backgroundColor = SkyTheme.skyColors.black.copy(alpha = 0.2f),
                            tint = SkyTheme.skyColors.black.copy(alpha = 0.2f)
                        )
                    } else {
                        Modifier
                    }
                ),
                url = tile.images.fourByThree ?: tile.images.sixteenByNine,
                mode = AspectRatio.FOUR_BY_THREE,
                imageCropsConfig = imageCropsConfig
            )

            if (tile.containsVideo) {
                TileVideoContentTimestampComponent(
                    tile = tile,
                    modifier = Modifier
                        .padding(start = 8.dp, bottom = 8.dp)
                        .hazeChild(state = hazeState, shape = RoundedCornerShape(2.dp))
                        .align(Alignment.BottomStart),
                    carouselTile = false
                )
                if (tile.contentLocked) {
                    LockedComponent(
                        contentTitle = tile.title,
                        modifier = imageSizeModifier
                    )
                }
            }
        }
```

**Comment by chrisbanes** [comment]
So this is likely because of #72 and #70 which where merged to actually get Haze working in previews and screenshot tests.

Looking at your screenshots, the difference is that the `TileVideoContentTimestampComponent` is now missing a background. Where was that background coming from? 

Paparazzi uses SDK 33 iirc, so I'm surprised this didn't crash previously tbh (for the same reason of #71).

**Comment by chrisbanes** [comment]
Sounds good. The background will be shown again as soon as #70 is fully fixed (I'm working on it this week).

I just don't know how it worked previously in Paparazzi 🤔. What version of Paparazzi are you using?
