### ISSUE TITLE
Top Bar with scaffold top bar content does not come below top bar  

### ISSUE THREAD

**Issue by fadiselim** [chrisbanes/haze#89]
Hey i tried your examples with top bar , i want to achieve something like the below image with android compose and scaffold, but top bar does not show the content below when it is inside scaffold even in the sample you have  with scaffold 
![Screenshot 2024-01-10 at 19 21 54](https://github.com/chrisbanes/haze/assets/10423608/c8c625cc-747c-43fd-ae03-5453f0626ace)

**Comment by chrisbanes** [comment]
Did you take a look at the samples? https://github.com/chrisbanes/haze/tree/main/sample

**Comment by fadiselim** [comment]
yes but on android the sample with scaffold does not have this behaviour, tested with android 14

**Comment by chrisbanes** [comment]
Yes, it does.

![Screenshot_1704963067](https://github.com/chrisbanes/haze/assets/227486/bd57dfcf-192f-4bd1-bf18-629d1b4314ca)
